config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tests do
    resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
    end

    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope -> { order(:title) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, counter_cache: true
  
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: :User, foreign_key: :author_id

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :body, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :body, uniqueness: { scope: :level,
    message: 'only one test of this kind per level' }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :by_category, -> (body) {
    joins(:category)
    .where(categories: {title: body})
    .order(body: :desc) }

  def self.select_title(body)
    by_category(body).pluck(:body)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_next_question, on: %i[create update]

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def current_question_number
    test.questions.order(:id).where('id <= ?', current_question.id).count
  end

  def successful?
    score_counter >= SUCCESS_PERCENT
  end

  def score_counter
    (correct_questions * 100) / test.questions.count
  end

  private

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) && correct_answers_count == answer_ids.count
  end

  def set_next_question
    if new_record?
      self.current_question = test.questions.first
    else
      self.current_question = next_question
    end
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: "Test", foreign_key: "author_id"

  validates :email, presence: true

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def show_passed_tests_by_level(level)
    tests.where(level: level)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to @answer, notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:destroy, :show, :edit, :update]
  before_action :find_test, only: [:create, :new]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def edit; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    
    if @question.save
      redirect_to test_questions_path(@test)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy!
    redirect_to test_path(@question.test)
  end

  private

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: %i[show edit update destroy start]
  before_action :set_user, only: :start

  
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def show; end

  def edit; end

  def update
    if @test.update(test_params)
      redirect_to test_path
    else
      render :edit
    end
  end
  
  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      redirect_to test_path(@test)
    else
      render :new
    end
  end

  def destroy
    @test.destroy!
    redirect_to tests_path
  end

  def start
    @user.tests.push(@test)
    redirect_to @user.test_passage(@test)
  end

  private

  def rescue_with_test_not_found
    render plain: 'Test was not found'
  end

  def find_test
    @test = Test.find(params[:id])
  end

  def set_test
    @test = Test.find(params[:id])
  end

  def set_user
    @user = User.first
  end
  
  def test_params
    params.require(:test).permit(:body, :level, :author_id, :category_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def github_url(author, repo)
    link_to "#{author}", "https://github.com/#{author}/#{repo}", target: :_blank
  end
end

app/helpers/footer_helper.rb
module FooterHelper
  def thinknetica_link
    link_to "Учебный проект в онлайн-школе Thinknetica", "http://thinknetica.com/", target: :_blank
  end
end

app/helpers/question_helper.rb
module QuestionHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.body} Question"
    else
      "Edit #{question.test.body} Question"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/time_helper.rb
module TimeHelper
  def current_year
    Time.current.year
  end
end

app/views/answers/_answer.html.erb
<li>
    <%= answer.body %><br>
    <%= link_to 'Show', answer_path(answer) %> |
    <%= link_to 'Edit' edit_answer_path(answer) %> |
    <%= link_to 'Delete',
                answer_path(answer),
                method: :delete,
                data:   { confirm: 'Are you sure?' } %>
</li>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>:
    <%= form.check_box :correct, id: :answer_correct %>
  </p>


  <p><%= form.submit %></p>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= link_to 'show', @answer %> |

<%= link_to 'back', question_path(@answer.question) %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>
<%= link_to 'Back', question_path(@question) %>

app/views/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', question_path(@answer.question) %>

app/views/questions/_form.html.erb
<%= form_with model: [@test, @question], local: true do |form| %>

  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p><br>
  
  <p>
    <%= form.submit %>
    <%= link_to "back", tests_path %>
  </p>
<% end %>

app/views/questions/_question.html.erb
<p><%= question.body %></p>
<style>
  p {
    margin-bottom: 40px;
  }
</style>
<table>
  <tr>
    <td>
      <%= link_to "delete", question_header(question), method: :delete %>
      |
    </td>
    <td>
      <%= link_to "edit", edit_test_path(question) %>
    </td>
  </tr>
</table>

app/views/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form' %>

app/views/questions/new.html.erb
<h1><%= question_header(@question, "Create New") %></h1>

<%= render "form" %>
<%= link_to "Back", test_questions_path(@question.test_id) %>

app/views/questions/show.html.erb
<h1><%= @question.test.body %> Question</h1>

<p>
  <%= @question.body %>
</p>

<h2>Answers</h2>

<%= link_to 'Add new answer', new_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'edit', edit_question_path(@question) %>
<%= link_to 'back', test_path(@question.test) %>

app/views/test_passages/result.html.erb
<h1><%= @test_passage.test.body %> Test was Completed!</h1>

<% if @test_passage.successful? %>
  <p>Congratulations! Your final score is <span class="success"><%= @test_passage.score_counter.to_i %></span></p>
<% else %>
  <p>Review the topic! Your final score is <span class="failure"><%= @test_passage.score_counter.to_i %></span></p>
<% end %>

<p>
  <%= link_to "Back to All Tests", tests_path %>
</p>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.body %> Test</h1>
<p>Question <%= @test_passage.current_question_number %> of <%= @test_passage.test.questions.size %></p>


<b>
  <%= @test_passage.current_question.body %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
    <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
      <tr>
        <td><%= b.label %></td>
        <td><%= b.check_box id: "answer_ids_#{b.object.id}" %></td>
      </tr>
    <% end %>

    <p><%= form.submit 'Next' %></p>
<% end %>